### ISSUE TITLE
External Secret - SecretSyncedError

### ISSUE THREAD

**Issue by zzbmmbzz** [external-secrets/external-secrets#1675]
Now, I have multi `Kubernetes Clusters on GCP and AWS Provider.`
On my GKE cluster, for easy way I create one `SecretStore` with aws auth used SecretRef. but when trying to create one ExternalSecret it return `SecretSyncedError`

SecretStore:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: aws_access_key_id
            name: awssm-secret-test
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: awssm-secret-test
      region: ap-northeast-1
      service: SecretsManager
```
and status after I apply the config:
```
kubectl get ss                                           
NAME               AGE   STATUS   READY
aws-secret-store   19m   Valid    True
```

ExternalSecret
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-registry-es-test
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: stg/abc/git-registry-Cdwxp9
    secretKey: registry
  refreshInterval: 5m
  secretStoreRef:
    kind: SecretStore
    name: aws-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: git-registry-secret
    template:
      data:
        .dockerconfigjson: '{{ .registry | toString }}'
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
```
The status after apply config
```
NAME                   STORE              REFRESH INTERVAL   STATUS              READY
git-registry-es-test   aws-secret-store   5m                 SecretSyncedError   False
```
The detail:
```
Status:
  Conditions:
    Last Transition Time:  2022-10-28T09:43:55Z
    Message:               could not get secret data from provider
    Reason:                SecretSyncedError
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age                   From              Message
  ----     ------        ----                  ----              -------
  Warning  UpdateFailed  2m30s (x32 over 17m)  external-secrets  RequestError: send request failed
caused by: Post "https://secretsmanager.ap-northeast-1.amazonaws.com/": net/http: invalid header field value for "Authorization"
```

AWS IAM that define in `awssm-secret-test` working normal and can get the secret by using AWS CLI

Could you please help me for this issue.

Thanks,

**Comment by moolen** [comment]
There could be a newline in your token, please see here: https://github.com/kubernetes/kubernetes/issues/52919

**Comment by zzbmmbzz** [comment]
> 
thank you for your help, @moolen . 
my issue has been fixed. <3

**Comment by suhas-chikkanna** [comment]
> > 
> 
> thank you for your help, @moolen . my issue has been fixed. <3

I am still facing this issue, can you please let me know how did you resolve this issue?

**Comment by SergeyMuha** [comment]
I had this issue as well.  I use Vault.
Secretstore works 
```yaml
apiVersion: v1
items:
- apiVersion: external-secrets.io/v1beta1
  kind: SecretStore
  metadata:
   .....
  spec:
    provider:
      vault:
        auth:
          kubernetes:
            mountPath: cluster
            role: cluster--tanzu-sync-secrets
            serviceAccountRef:
              name: tanzu-sync-vault-sa
        namespace: ""
        path: secret
        server: http://vault....../
        version: v2
  status:
    capabilities: ReadWrite
    conditions:
    - lastTransitionTime: "2024-05-07T14:22:06Z"
      message: store validated
      reason: Valid
      status: "True"
      type: Ready
```
but Externalsecret doesn't
```yaml
- apiVersion: external-secrets.io/v1beta1
  kind: ExternalSecret
 .....
  spec:
    data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/dev/cluster/tanzu-sync/sync-git/ssh
        property: privatekey
      secretKey: ssh-privatekey
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: secret/dev/cluster/tanzu-sync/sync-git/ssh
        property: knownhosts
      secretKey: ssh-knownhosts
    refreshInterval: 1m
    secretStoreRef:
      kind: SecretStore
      name: tanzu-sync-secrets
    target:
      creationPolicy: Owner
      deletionPolicy: Retain
  status:
    conditions:
    - lastTransitionTime: "2024-05-08T09:09:33Z"
      message: could not get secret data from provider
      reason: SecretSyncedError
      status: "False"
      type: Ready
```
Root cause was the mismatch between secret-engine version in Vault and version in SecretStore `spec.provider.vault.version`
```yaml . I upgraded to version 2
#Enable KV v2 at secret/.
 vault secrets enable -path=secret kv-v2

#If the KV version is version:1, upgrade it to version:2.
 vault kv enable-versioning secret/
```
