### ISSUE TITLE
'unable to validate store' errors in 0.6.0

### ISSUE THREAD

**Issue by DavidR91** [external-secrets/external-secrets#2035]
**Setup**
This is a GCP secret sync. There is a single cluster secret store and all external secrets reference that store.

The setup works, the secrets all sync fine etc.

Almost all of these secrets are configured with a refresh interval of 0 to disable auto refresh since it is not applicable here.

**Issue**
Every so often (every ~3 months) some `ExternalSecret` resources (but not all) enter an error state with 
```
SecretSyncedError: could not use store reference
```
By the time this state is noticed, the store appears to be healthy already - but the secrets remain in this error state until they are `Replace`d in kubernetes, at which point they immediately return to a healthy state.

In the controller, this is the actual detail of what is happening:

```json
{"level":"error","ts":1676785035.9511597,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/gcp-cluster","error":"could not get provider client: failed to create GCP secretmanager client: unable to fetch pod token: Post \"https://10.94.0.1:443/api/v1/namespaces/external-secrets/serviceaccounts/external-secrets/token\": read tcp 10.93.8.131:43702->10.94.0.1:443: read: connection reset by peer","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
{"level":"error","ts":1676785035.9681344,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","clusterSecretStore":{"name":"gcp-cluster"},"namespace":"","name":"gcp-cluster","reconcileID":"191ae46a-552c-41fe-bd95-fa99dc185580","error":"could not get provider client: failed to create GCP secretmanager client: unable to fetch pod token: Post \"https://10.94.0.1:443/api/v1/namespaces/external-secrets/serviceaccounts/external-secrets/token\": read tcp 10.93.8.131:43702->10.94.0.1:443: read: connection reset by peer","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

readable error:
```
"could not get provider client: failed to create GCP secretmanager client: unable to fetch pod token: Post \"https://10.94.0.1:443/api/v1/namespaces/external-secrets/serviceaccounts/external-secrets/token\": read tcp 10.93.8.131:43702->10.94.0.1:443: read: connection reset by peer
```

readable stacktrace:
```
github.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile
    /home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:54
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
    /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234
```

It seems as though this error that is being hit is a temporary situation that should be retried - but the behaviour we're seeing is that it kind of just stops?

Admittedly didn't try restarting the ES controller - but other than that, it seems the only thing that returns it to healthy on these secrets is replacing them.

**Comment by gusfcarvalho** [comment]
Hi @DavidR91 ! We do not support fixes to previous versions. Would you mind seeing if the issue still persists on 0.7.2?

**Comment by gusfcarvalho** [comment]
Im afraid not! We fixed several things from 0.6.0 to 0.7.2 (including some GCP related issues). Since you do not have a long reconcile loop, it might be hard to understand what’s going on (my guess is something related with Auth, which some fixes were provided in 0.7.2)

**Comment by gusfcarvalho** [comment]
Also, from your error it seems to be related with your kubeapiserver connection (some flakiness in there), so that might be a good place to double-check.

**Comment by L1ghtman2k** [comment]
@gusfcarvalho , the issue persists in 0.9.16. 

Our workflow is as follows:

 - Deploy secret store
 - Deploy External Secret that depends on secret store.

if the secret store was in a not-ready state at the time the external secret is created, then the external secret doesn't get generated, even if secret store later gets in a healthy state
