### ISSUE TITLE
For GCP, property field of remoteRef in ExternalSecret is not working

### ISSUE THREAD

**Issue by k-p-ani** [external-secrets/external-secrets#210]
Not able to access credential from GCP. I have my secrets created with name **git-creds** and stored in GCP as json format as below.
{"**git-token**": "my-token", "**git-username**": "my-user"} 

Below Is my ExternalSecret yaml file.

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gitlab-creds
spec:
  refreshInterval: 1m           
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-store               
  target:
    name: **gcp-secret**   
    creationPolicy: Owner
  data:
  - secretKey: accesskey  # key to be used in Kubernetes Secret for one of the data
    remoteRef:
      key: **git-creds**.     # name of GCP secret 
      version: "3"
      property: **_git-username_**.    # key used in the  GCP secret json file
 
_When Kubernetes Secret is created , instead of getting specific property (**git-username**) from json file , I see secret containing complete json file {"**git-token**": "my-token", "**git-username**": "my-user"} in base64_

 **When I add another entry of secretKey, to capture other value (git-token) from json, like below**  
  data:
  - secretKey: accesskey  # key to be used in Kubernetes Secret for one of the data
    remoteRef:
      key: **git-creds**.     # name of GCP secret 
      version: "3"
      property: **_git-username_**.    # key used in the  GCP secret json file
  - secretKey: secretkey  # key to be used in Kubernetes Secret for other data
    remoteRef:
      key: **git-creds**.     # name of GCP secret 
      version: "3"
      property: **_git-token_**.    # key used in the  GCP secret json file

then I am getting below error

_2021-06-22T14:47:26.086Z        ERROR   controllers.ExternalSecret      could not reconcile ExternalSecret      {"ExternalSecret": "default/gitlab-creds", "SecretStore": "default/gcp-secret-store", "error": "could not get secret data from provider: key \"git-creds\" from ExternalSecret \"gitlab-creds\": unable to access Secret from SecretManager Client: rpc error: code = Canceled desc = grpc: the client connection is closing"}_

Note:- I didn't find any proper and complete example for GCP. 
I followed below link, which I feel has some incorrect comments, for **secretKey**, the comment says GCPSM secret key, should it be GCPSM key or the key to be used in Kubernetes Secret
https://external-secrets.io/provider-google-secrets-manager/

Also in the same link there is a verification step as below
kubectl get secret secret-to-be-created -n <namespace> | -o jsonpath='{.data.example-externalsecret-key}' | base64 -d

here field **example-externalsecret-key**, is no where referred in the example **ExternalSecret** given in above link. Should **example-externalsecret-key**, be referred in **secretKey**, in the example

Thanks
Ani.

**Comment by knelasevero** [comment]
remoteRef property for getting inner keys from a json string is not yet supported for GCP. PRs are welcome (right now you can only get a single string value)! :smile: 

Yes, you are right, the docs are wrongly referencing a key that is not there. This must be fixed. I will open a specific issue for that.

**Comment by knelasevero** [comment]
Opened this one: https://github.com/external-secrets/external-secrets/issues/211

**Comment by k-p-ani** [comment]
oh,
seems like due to this limitation we have to fall back to kubernetes external secrets implementation (https://github.com/external-secrets/kubernetes-external-secrets)

**Comment by knelasevero** [comment]
I am going to implement this one and let you know.

**Comment by knelasevero** [comment]
please trying getting latest release :) This should work now.

```
helm repo update

helm install external-secrets \
   external-secrets/external-secrets \
    -n external-secrets \
    --create-namespace
```

**Comment by thecodeassassin** [comment]
@knelasevero for me this still doesn't seem to work (or I'm doing something wrong)

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 1h           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: x-secrets               # name of the SecretStore (or kind specified)
  target:
    name: test  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: "connection_name"
    remoteRef:
      key: "database-secret-development"
      property: dsn. # key used in the GCP secret json file

```

error: 

```could not get secret data from provider: key "database-secret-development" from ExternalSecret "test": key dsn. does not exist in secret database-secret-developmen
```
