### ISSUE TITLE
alpha feature "Targeting Custom Resources" - "Advanced Path Targeting" templating works not as expected

### ISSUE THREAD

**Issue by Sven1410** [external-secrets/external-secrets#5587]
ESO version 1.00

this works as expected:

```
  templateFrom:
    - literal: |
        slack:
          api_url: https://www.whatever.com
      target: spec
```

this is not working:

```
    template:
      engineVersion: v2
      templateFrom:
        - literal: |
            api_url: https://www.whatever.com
          target: spec.slack
```

produces:

_"msg":"unknown field \"spec.slack.slack\"","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret",..._

additionally, this is also not working:

```
      templateFrom:
        - literal: |
            slack:
              api_url: {{ .url }}
          target: spec
```

with: 

```
  data:
    - secretKey: url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None   
        metadataPolicy: None
        key: vaultpath/asecretinvault
```

it produces:

_"unknown field \"spec.slack.api_url.url\"","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":..._

**Comment by Skarlso** [comment]
I'll take a look. Thanks for reporting.

**Comment by Skarlso** [comment]
Got it. Cheeky bastard of a bug. :D

**Comment by Sven1410** [comment]
unfortunately it is still not working correctly (v 1.1.0 now) - two problems:

(1)
when I use:

```
    template:
      engineVersion: v2
      templateFrom:
        - literal: |             
            api_url: {{ .url }}
          target: spec.slack
  data:
    - secretKey: url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None   
        metadataPolicy: None
        key: vaultpath/asecretinvault
```

it results in the error: "could not update secret" the controller writes:
`
"msg":"unknown field \"spec.slack.api_url.url\"","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":...`

(2)

this works:

```
 target:
    name: notifier-slack-test-dev
    creationPolicy: Merge
    manifest:
      apiVersion: ...
      kind: ...
    template:
      engineVersion: v2
      templateFrom:
        - literal: |             
            api_url: "https://www.sdfsfnothing.com"
          target: spec.slack
```

**but** it erases the complete "spec" path in the target CR - the contents are not merged with that what is in the current CR under "spec".
Maybe this is expected (?) 
Is it possible to make only changes in the dept of "spec.slack" or even better in "spec.slack.api_url" directly?

 @Skarlso - would be cool if you can have a look again, thanks in advance!

**Comment by Skarlso** [comment]
Hmm. It's should navigate to that place and if it doesn't exist that's when it creates it. Otherwise it should have just set the field. Odd. I even have a test for that I think. I'll take a look when I'm back from vacation next week. 👍

**Comment by Sven1410** [comment]
@Skarlso 
I've tested v1.1.1 today and unfortunately it is still not working:

- it is not merging the field(s) and still erases the complete target - e.g. `target: spec.slack`
- `api_url: {{ .url }}` still produces an error: _unknown field \"spec.slack.api_url.url\"_

can you have a look again? thanks in advance!

**Comment by Skarlso** [comment]
Huh, what the hell? :D I even have tests for it. 🤔

**Comment by Sven1410** [comment]
maybe I'm doing something wrong? I will attach my full (anonymized) yaml:

```
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-myname-notifier-slack
spec:
  refreshPolicy: CreatedOnce # normally it is never changed
  secretStoreRef:
    name: vault-secret-store-myone
    kind: ClusterSecretStore
  target:
    name: notifier-slack-test-dev
    #creationPolicy: Merge
    manifest:
      apiVersion: monitoring.monitoringproduct.io/v1alpha1
      kind: MonitoringProductNotifier
    template:
      engineVersion: v2
      templateFrom:
        - literal: |             
            api_url: "https://www.sdfsfnothing.com"
          target: spec.slack
        #api_url: {{ `{{ .url }}` }}
  data:
    - secretKey: url
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None   
        metadataPolicy: None
        key: slack-alerts/mysecretname-alerts-dev
```

**Comment by Skarlso** [comment]
That, looks okay, I think. I'll investigate. :D

**Comment by Skarlso** [comment]
Can you try the attached PR please? https://github.com/external-secrets/external-secrets/pull/5735

**Comment by Sven1410** [comment]
I would like to test it - but I failed with a beginner problem :-( 
how can I reference the image from your build/PR? 
I tried "-our proxy for ghcr repo-/external-secrets/external-secrets@sha256:2d0fed3fc4dbb1a48431fb780a7e7f3c7f4c749a" but that is not working unfortunately.

**Comment by Skarlso** [comment]
Ah, no worries, let me build one for you.

**Comment by Skarlso** [comment]
Should be `ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty`.

**Comment by Sven1410** [comment]
`Failed to pull image "ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty": rpc error: code = NotFound desc = get image config descriptor: no match for platform in manifest sha256:f1867ef1c858e46fbe0a5e25e2dce72bd08c10e5fb25d0007db5fc23ab07c2c2: not found`

**Comment by Skarlso** [comment]
huh

**Comment by Skarlso** [comment]
Oh wait, what's your OS?

**Comment by Sven1410** [comment]
I think it must be gardenlinux

**Comment by Skarlso** [comment]
What Arch?

**Comment by Sven1410** [comment]
amd64

**Comment by Skarlso** [comment]
```
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
                go build -tags all_providers -o 'bin/external-secrets-linux-amd64' main.g
```

weird. I have that in there. :/

**Comment by Skarlso** [comment]
Okay, I _think_ I fixed it. Can you try again?

**Comment by Sven1410** [comment]
should I try the same image name/sha ? 

for this I still see :
`
Failed to pull image "ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty": rpc error: code = NotFound desc = get image config descriptor: no match for platform in manifest sha256:fab80975f847bf6f4a0fdcf2816a0dea537dae20423dd7c55d19be72deaed23a: not found`

**Comment by Skarlso** [comment]
Are you running `docker pull ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty`?

**Comment by Sven1410** [comment]
I changed the image in the deployment, to:

`image: ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty` 

the events are:

`Pulling image "ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty"`

`Error: ErrImagePull`

`Failed to pull image "ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty": rpc error: code = NotFound desc = get image config descriptor: no match for platform in manifest sha256:fab80975f847bf6f4a0fdcf2816a0dea537dae20423dd7c55d19be72deaed23a: not found`

**Comment by Skarlso** [comment]
Gotcha. That is super annoying. :D

**Comment by Skarlso** [comment]
<img width="877" height="536" alt="Image" src="https://github.com/user-attachments/assets/4a594a7b-61a1-4c6b-aa56-9edeb9f67b25" />

Ah okay, something definitely did not work. Let me try to redo this.

**Comment by Skarlso** [comment]
Finally, maybe `ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty-3` does it.

**Comment by Sven1410** [comment]
`image: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Askarlso%2Fexternal-secrets%3Apull&service=ghcr.io: 401 Unauthorized`

**Comment by Skarlso** [comment]
Ops, sorry. Made it public.

**Comment by Sven1410** [comment]
sorry - still: 

`Failed to pull image "ghcr.io/skarlso/external-secrets:v1.1.1-38.g2d0fed3fc.dirty-3": rpc error: code = NotFound desc = get image config descriptor: no match for platform in manifest sha256:9dffc5a4267982f81f50a5ba3bfbd3a39b5bbef7b4c0e747042dd77aa84b084f: not found`

**Comment by Skarlso** [comment]
ARGH. Sorry, you'll have to wait for a release then. :/

**Comment by Sven1410** [comment]
@Skarlso  - today I've tested v1.2.1:
the merging works now correctly - thanks for your efforts here.
unfortunately there is still a problem if "advanced templating" is used.
  
this fails:
  
```
spec:
  ...
  target:
    name: notifier-slack-test-dev
    creationPolicy: Merge
    ...
    template:
      engineVersion: v2
      templateFrom:
        - literal: |       
            api_url: {{ .url }}      
          target: spec.slack
  data:
    - secretKey: url
      remoteRef:        
        key: slack-alerts/mysecret-alerts-dev
```


result: _"msg":"unknown field \"spec.slack.url\"","controller":"externalsecret",..._ 
(which is correct - the target resource accepts only "spec.slack.api_url" not "spec.slack.url")
It looks like it tries to **replace** the field "api_url" with "url". 

this works: 

```
spec:
  ...
  target:
    name: notifier-slack-test-dev
    creationPolicy: Merge
    ...
    template:
      engineVersion: v2
      templateFrom:
        - literal: |       
            api_url: {{ .api_url }}
          target: spec.slack 
  dataFrom:
    - extract:
        key: slack-alerts/mysecret-alerts-dev
      rewrite:
      - regexp:
          source: "url"
          target: "api_url"
```
		  
for my use-case this is sufficient - but it does not match what is described in the documentation.
(https://external-secrets.io/latest/guides/targeting-custom-resources/#advanced-path-targeting)
or is something wrong in my external-secrets spec?

**Comment by Skarlso** [comment]
I'm not following. :D What's the problem? It correctly errored out because the field did not exist.

**Comment by Sven1410** [comment]
I expected that 
`api_url: {{ .url }}    ` 
sets the field "api_url" with the content from the secret.
but it looks like it tries to **add** a field named "url" - which is wrong

**Comment by Skarlso** [comment]
Interesting. I can't reproduce this atm with a unit test. 🤔  There has to be a different issue somewhere. 🤔

**Comment by Sven1410** [comment]
I tested the other way around: 
` footer: {{ .api_url }}`
it works correctly and replaces the content in "footer".

also this works correctly:

```
    template:
      engineVersion: v2
      templateFrom:
        - literal: |       
            api_url: {{ .url }}
          target: spec.slack
  dataFrom:
    - extract:
        key: slack-alerts/myalert-dev
      rewrite:
      - regexp:
          source: "nothing"
          target: "tonothing"
```
		  
this is still not working: 
```

    template:
      engineVersion: v2
      templateFrom:
        - literal: |       
            api_url: {{ .url }}
          target: spec.slack
  data:
    - secretKey: url
      remoteRef:
        key: slack-alerts/myalert-dev	
```	  
		  
it produces:
		  
```
{"level":"info","ts":1767860326.365289,"logger":"controllers.ExternalSecret","msg":"updating target resource","ExternalSecret":...
{"level":"info","ts":1767860326.4246106,"msg":"unknown field \"spec.slack.api_url.url\"","controller":"externalsecret",...
{"level":"error","ts":1767860326.4248848,"msg":"Reconciler error","controller":"externalsecret",...
```

so the behaviour is different when I use "dataFrom:" instead of "data:" for the secret (in vault).
the secret itself in vault contains only one key/field named "url".

**Comment by Sven1410** [comment]
I played a little bit with the nonworking case: 

```
    template:
      engineVersion: v2
      templateFrom:
        - literal: |     
            {{- range $key, $val := .url }}
            api_url: {{ .val }}
            {{- end }}
          target: spec.slack
  data:
    - secretKey: url
      remoteRef:
        key: slack-alerts/myalert-dev
```

the result is:

`at <.url>: range can't iterate over {\"url\":\"https://hooks.slack.com/services/secretkey....\"}"`

then I tested:

```
  - literal: |    
      api_url: {{ printf "%s" .url | quote }}
```

it templates without errors, result in cr is:

` api_url: {"url":"https://hooks.slack.com/services/secretkey..."}`

so it looks like that in case of "data:" the ".url" is just an object instead of string ...

**Comment by Skarlso** [comment]
Thanks for the extra info!

**Comment by Skarlso** [comment]
Ah yes. With data you need to define a property if you want one thing because data is a map there.

Use:
```yaml
  data:
    - secretKey: url
      remoteRef:
        key: slack-alerts/myalert-dev
        property: url
```

**Comment by Sven1410** [comment]
Thanks, that works now. 👍great.
But that's not obvious - should we maybe add a hint to the documentation about this? 
I think I would not be able to find that out by myself. 
I could also not find out where this behaviour of "property:" is described (maybe I have overseen it?)

**Comment by Skarlso** [comment]
Hm, hm, some of it is described in the API. I'm not sure where we could document that. If we do that would be on the API doc here: https://external-secrets.io/latest/api/externalsecret/ which somewhat already has some things. Since it's part of that object's spec. :)

**Comment by Sven1410** [comment]
I think it would be sufficient to mention it here as a short hint (blue box):
https://external-secrets.io/latest/guides/targeting-custom-resources/#advanced-path-targeting 
I also think the example in this section must be fixed it has also no "property:" fields.

**Comment by Sven1410** [comment]
@Skarlso

the feature itself works fine now. There is a last problem open:
It cannot register an informer for the target resource:

`failed to register informer for generic target, drift detection may not work","ExternalSecret":{"name":"externalsecret-test-dev-notifier-slack","namespace":"monitoring"},"group":"monitoring.chronosphere.io","version":"v1alpha1","kind":"ChronosphereNotifier","error":"failed to get informer for monitoring.chronosphere.io/v1alpha1, Kind=ChronosphereNotifier: no kind \"ChronosphereNotifier\" is registered for version \"monitoring.chronosphere.io/v1alpha1\" in scheme ...`

the listed data for group/version/kind is 100% correct. It also updates the target resource correctly. I think I set the RBAC correctly for this CR.

```
k explain chronospherenotifiers
GROUP:      monitoring.chronosphere.io
KIND:       ChronosphereNotifier
VERSION:    v1alpha1
```

So something in this Informer registration must be wrong. 
or is it not correct to use `creationPolicy: Merge` ?

[https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L726](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L726)

**Comment by Sven1410** [comment]
@Skarlso

the problem is even worse now: I have a cluster with 7 of these custom target resources (ChronosphereNotifier). Here the operator enters a infinite refresh-loop for the external-secrets. (the _**"failed to register informer for generic target"**_ occurs around 10 times per second now, it contactes vault and updates the timestamp of the ExternalSecret)

```
status:
  binding:
    name: '' <---- always empty
  conditions:
    - lastTransitionTime: '2026-02-05T16:04:21Z' <---- not updated 
      message: secret synced
      reason: ResourceSynced
      status: 'True'
      type: Ready
  refreshTime: '2026-02-06T08:42:59Z'   <---- updated several times per second
  syncedResourceVersion: 1-897abc809a40f1dcd194fb35...
```
problem occurs in  v1.3.2 and v1.2.1
-the target resource is updated (correctly)
-debug logs from operator show no helpful things, just the refresh loop is reported

**Comment by Sven1410** [comment]
interestingly I could not stop the reconcile-loop with setting 
`refreshInterval: 0s`
that surprises me because of (line748): 
https://github.com/external-secrets/external-secrets/blame/main/pkg/controllers/externalsecret/externalsecret_controller.go#L748

```
	// if the refresh interval is <= 0, we should not requeue
	if refreshInterval <= 0 {
		return ctrl.Result{}
	}
```

**Comment by Skarlso** [comment]
Hmmm. That's interesting. Did these occur before?

**Comment by Sven1410** [comment]
the _"failed to register informer for generic target"_ error was there from the beginning (for targets of type "ChronosphereNotifier")
registering informers works e.g. for Configmaps
I think it started to loop when I enabled multiple targets of type "ChronosphereNotifier"
It stops the loop when I delete and recreate one of the ExternalSecrets. But after some time it loops again ...

**Comment by Skarlso** [comment]
Gotcha. I _think_ I see the problem. I'll try to fix it later today.

**Comment by Skarlso** [comment]
Okay, the fix is merged, let's see if it will actually do the thing right this time. :)

**Comment by Skarlso** [comment]
I will try run it on my own later today in a couple of scenarios.

**Comment by Sven1410** [comment]
that looks good now, thanks!
I've tested the image with tag "main" (https://external-secrets.io/latest/guides/using-latest-image/):
- no refresh looping anymore 
- Informer could be registered 
- drift detection works (manual change in target resource was corrected immediately)

**Comment by Skarlso** [comment]
Yiiiiiissss 🎉 🎉 🎉 

Fantastic news! :) 👍  Thanks so much for testing.
