### ISSUE TITLE
Too many Azure Key Vault API requests when using dataFrom.find in an ExternalSecret

### ISSUE THREAD

**Issue by devblackops** [external-secrets/external-secrets#5755]
**Describe the bug**

When using `dataFrom.find` with an `ExternalSecret`, the Azure Key Vault provider performs an abnormally large amount of `SecretList` API operations and doesn't honor the `refreshInterval` if it doesn't find a matching Key Vault secret. Once a Key Vault secret is created that matches the regex in `dataFrom.Find`, it returns to normal and only queries Key Vault according to the `refreshInterval`. 

**To Reproduce**

1. Create an `ExternalSecret` resource to query Key Vault every `10m` for secrets with a `foo` prefix and to drop the `foo` prefix from the resultant k8s secret.
```yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: foo
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      name:
        regexp: ^foo-.*
    rewrite:
    - regexp:
        source: ^foo-(.*)
        target: $1
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: kv
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: app-secrets
```
2. Observer that the `ExternalSecret` has a `SecretDeleted` status. This is normal, as the `ExternalSecret` can't find a matching Key Vault Secret because it hasn't been created yet.
3. Check Key Vault logs and observe that ESO is calling `SecretList` operations many times a second and doesn't honor the `10m` refreshInterval. **THIS IS THE PROBLEM**.
4. Create a `foo-mysecret` Key Vault secret.
5. Observe that ESO finds the Key Vault secret and creates a matching k8s secret called `app-secrets` with a key of `mysecret`.
6. ESO then only queries Key Vault every `10m`, or whatever the `refreshinterval` is set to.

k8s version: `1.33.5`
ESO version: `0.16.2`

**Expected behavior**
ESO should honor the given `refreshInterval` on the `ExternalSecret`. If there are too many ExternalSecrets all doing `SecretList` operations multiple times a second, there is a risk of running into Key Vault rate limits, and all these unnecessary Key Vault API calls start costing real money.

**Screenshots**

**Additional context**
We automatically create an `ExternalSecret` in every app namespace that queries Key Vault for secrets with a prefix that matches the namespace name. We have a separate process that populates Key Vault secrets and prefixes them with whatever namespace the secrets are intended for. We are running into heavy Key Vault API usage when application namespaces are provisioned, but we haven't distributed the matching Key Vault secrets yet. At scale, we can run into Key Vault rate limiting issues, and unnecessary Key Vault costs due to heavy API usage.

**Comment by gusfcarvalho** [comment]
hi @devblackops . You need to upgrade your ESO version -- this is something we already addressed regarding the `SecretDeleted` state, if I recall correctly (it was being reported as an error state, causing exponential backoff to happen).

**Comment by devblackops** [comment]
@gusfcarvalho We're aware we need to upgrade, but we still have some v1beta1 resources deployed and can't upgrade to 0.17.0+ until those are removed. Can you point me to the version that this may have been fixed in? It's not immediately obvious from the release notes.

**Comment by evrardjp** [comment]
Tagged as invalid as the bug seem to have been fixed in the past, according to @gusfcarvalho .

**Comment by evrardjp** [comment]
(You might also be interested by latest release which includes a compat flag that will be deprecated as soon as june).
