### ISSUE TITLE
Limit retry and do exponential backoff when initial secret request fail

### ISSUE THREAD

**Issue by maggiezhangdong** [external-secrets/external-secrets#646]
Make initial secret request retry times configurable (like stop requesting after 3 failed request); or exponential backoff when initial secret retrieval fails.

Currently when there is a misconfiguration, ExternalSecret keeps requesting Vault server every 30s.
https://github.com/external-secrets/external-secrets/blob/c00afc9ff7575b37b4e332e214c270fc25bb09ae/pkg/controllers/externalsecret/externalsecret_controller.go#L43

Hope to limit impact to Vault server when initial secret retrieval fails.

**Comment by moolen** [comment]
When we get rid of the `requeueAfter` and replace it with `Requeue: true` then we get exponential backoff.

I think this is the only occurrence where it is problematic to use a static `requeueAfter` duration is here:

https://github.com/external-secrets/external-secrets/blob/c00afc9ff7575b37b4e332e214c270fc25bb09ae/pkg/controllers/externalsecret/externalsecret_controller.go#L221-L238

If we would just return an error OR set Requeue=true then we get exp backoff. I don't think we need this to be configurable.  [controller-runtime does that already for us](https://github.com/kubernetes-sigs/controller-runtime/blob/4d6d8ef2bb3191239ccc958691b790854b83faa3/pkg/internal/controller/controller.go#L311-L328).

**Comment by moolen** [comment]
This was fixed with the above mentioned PR

**Comment by neggert** [comment]
I'm still seeing a request every 30 seconds when trying to retrieve a secret from Hashicorp Vault that  the system doesn't have permission to read. Does this instance need to be modified as well as in #934?

https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L240

**Comment by moolen** [comment]
Hey @neggert i think that can be changed as well. Feel free to open a PR for that :pray:
